// Generated by gencpp from file manual_srvs/ManualSrv.msg
// DO NOT EDIT!


#ifndef MANUAL_SRVS_MESSAGE_MANUALSRV_H
#define MANUAL_SRVS_MESSAGE_MANUALSRV_H

#include <ros/service_traits.h>


#include <manual_srvs/ManualSrvRequest.h>
#include <manual_srvs/ManualSrvResponse.h>


namespace manual_srvs
{

struct ManualSrv
{

typedef ManualSrvRequest Request;
typedef ManualSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManualSrv
} // namespace manual_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manual_srvs::ManualSrv > {
  static const char* value()
  {
    return "cb9460bf78e499f0b8513944c7615a57";
  }

  static const char* value(const ::manual_srvs::ManualSrv&) { return value(); }
};

template<>
struct DataType< ::manual_srvs::ManualSrv > {
  static const char* value()
  {
    return "manual_srvs/ManualSrv";
  }

  static const char* value(const ::manual_srvs::ManualSrv&) { return value(); }
};


// service_traits::MD5Sum< ::manual_srvs::ManualSrvRequest> should match
// service_traits::MD5Sum< ::manual_srvs::ManualSrv >
template<>
struct MD5Sum< ::manual_srvs::ManualSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manual_srvs::ManualSrv >::value();
  }
  static const char* value(const ::manual_srvs::ManualSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manual_srvs::ManualSrvRequest> should match
// service_traits::DataType< ::manual_srvs::ManualSrv >
template<>
struct DataType< ::manual_srvs::ManualSrvRequest>
{
  static const char* value()
  {
    return DataType< ::manual_srvs::ManualSrv >::value();
  }
  static const char* value(const ::manual_srvs::ManualSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manual_srvs::ManualSrvResponse> should match
// service_traits::MD5Sum< ::manual_srvs::ManualSrv >
template<>
struct MD5Sum< ::manual_srvs::ManualSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manual_srvs::ManualSrv >::value();
  }
  static const char* value(const ::manual_srvs::ManualSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manual_srvs::ManualSrvResponse> should match
// service_traits::DataType< ::manual_srvs::ManualSrv >
template<>
struct DataType< ::manual_srvs::ManualSrvResponse>
{
  static const char* value()
  {
    return DataType< ::manual_srvs::ManualSrv >::value();
  }
  static const char* value(const ::manual_srvs::ManualSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANUAL_SRVS_MESSAGE_MANUALSRV_H
