// Generated by gencpp from file manual_srvs/ManualSrvResponse.msg
// DO NOT EDIT!


#ifndef MANUAL_SRVS_MESSAGE_MANUALSRVRESPONSE_H
#define MANUAL_SRVS_MESSAGE_MANUALSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manual_srvs
{
template <class ContainerAllocator>
struct ManualSrvResponse_
{
  typedef ManualSrvResponse_<ContainerAllocator> Type;

  ManualSrvResponse_()
    : success(false)  {
    }
  ManualSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ManualSrvResponse_

typedef ::manual_srvs::ManualSrvResponse_<std::allocator<void> > ManualSrvResponse;

typedef boost::shared_ptr< ::manual_srvs::ManualSrvResponse > ManualSrvResponsePtr;
typedef boost::shared_ptr< ::manual_srvs::ManualSrvResponse const> ManualSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manual_srvs::ManualSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manual_srvs::ManualSrvResponse_<ContainerAllocator1> & lhs, const ::manual_srvs::ManualSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manual_srvs::ManualSrvResponse_<ContainerAllocator1> & lhs, const ::manual_srvs::ManualSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manual_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::manual_srvs::ManualSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manual_srvs/ManualSrvResponse";
  }

  static const char* value(const ::manual_srvs::ManualSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::manual_srvs::ManualSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManualSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manual_srvs::ManualSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manual_srvs::ManualSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANUAL_SRVS_MESSAGE_MANUALSRVRESPONSE_H
