(cl:defpackage mycobot_communication-msg
  (:use )
  (:export
   "<MYCOBOTANGLES>"
   "MYCOBOTANGLES"
   "<MYCOBOTCOORDS>"
   "MYCOBOTCOORDS"
   "<MYCOBOTGRIPPERSTATUS>"
   "MYCOBOTGRIPPERSTATUS"
   "<MYCOBOTPUMPSTATUS>"
   "MYCOBOTPUMPSTATUS"
   "<MYCOBOTSETANGLES>"
   "MYCOBOTSETANGLES"
   "<MYCOBOTSETCOORDS>"
   "MYCOBOTSETCOORDS"
   "<MYCOBOTSETENDTYPE>"
   "MYCOBOTSETENDTYPE"
   "<MYCOBOTSETFRESHMODE>"
   "MYCOBOTSETFRESHMODE"
   "<MYCOBOTSETTOOLREFERENCE>"
   "MYCOBOTSETTOOLREFERENCE"
  ))

