// Generated by gencpp from file manual_srvs/SetJointAnglesRequest.msg
// DO NOT EDIT!


#ifndef MANUAL_SRVS_MESSAGE_SETJOINTANGLESREQUEST_H
#define MANUAL_SRVS_MESSAGE_SETJOINTANGLESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manual_srvs
{
template <class ContainerAllocator>
struct SetJointAnglesRequest_
{
  typedef SetJointAnglesRequest_<ContainerAllocator> Type;

  SetJointAnglesRequest_()
    : angles()  {
      angles.assign(0.0);
  }
  SetJointAnglesRequest_(const ContainerAllocator& _alloc)
    : angles()  {
  (void)_alloc;
      angles.assign(0.0);
  }



   typedef boost::array<double, 6>  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointAnglesRequest_

typedef ::manual_srvs::SetJointAnglesRequest_<std::allocator<void> > SetJointAnglesRequest;

typedef boost::shared_ptr< ::manual_srvs::SetJointAnglesRequest > SetJointAnglesRequestPtr;
typedef boost::shared_ptr< ::manual_srvs::SetJointAnglesRequest const> SetJointAnglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator1> & lhs, const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angles == rhs.angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator1> & lhs, const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manual_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9251d0f23d6395e464faacefad00bbd4";
  }

  static const char* value(const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9251d0f23d6395e4ULL;
  static const uint64_t static_value2 = 0x64faacefad00bbd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manual_srvs/SetJointAnglesRequest";
  }

  static const char* value(const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] angles\n"
;
  }

  static const char* value(const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointAnglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manual_srvs::SetJointAnglesRequest_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANUAL_SRVS_MESSAGE_SETJOINTANGLESREQUEST_H
