// Generated by gencpp from file manual_srvs/SetJointAngles.msg
// DO NOT EDIT!


#ifndef MANUAL_SRVS_MESSAGE_SETJOINTANGLES_H
#define MANUAL_SRVS_MESSAGE_SETJOINTANGLES_H

#include <ros/service_traits.h>


#include <manual_srvs/SetJointAnglesRequest.h>
#include <manual_srvs/SetJointAnglesResponse.h>


namespace manual_srvs
{

struct SetJointAngles
{

typedef SetJointAnglesRequest Request;
typedef SetJointAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointAngles
} // namespace manual_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manual_srvs::SetJointAngles > {
  static const char* value()
  {
    return "cb9460bf78e499f0b8513944c7615a57";
  }

  static const char* value(const ::manual_srvs::SetJointAngles&) { return value(); }
};

template<>
struct DataType< ::manual_srvs::SetJointAngles > {
  static const char* value()
  {
    return "manual_srvs/SetJointAngles";
  }

  static const char* value(const ::manual_srvs::SetJointAngles&) { return value(); }
};


// service_traits::MD5Sum< ::manual_srvs::SetJointAnglesRequest> should match
// service_traits::MD5Sum< ::manual_srvs::SetJointAngles >
template<>
struct MD5Sum< ::manual_srvs::SetJointAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manual_srvs::SetJointAngles >::value();
  }
  static const char* value(const ::manual_srvs::SetJointAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manual_srvs::SetJointAnglesRequest> should match
// service_traits::DataType< ::manual_srvs::SetJointAngles >
template<>
struct DataType< ::manual_srvs::SetJointAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::manual_srvs::SetJointAngles >::value();
  }
  static const char* value(const ::manual_srvs::SetJointAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manual_srvs::SetJointAnglesResponse> should match
// service_traits::MD5Sum< ::manual_srvs::SetJointAngles >
template<>
struct MD5Sum< ::manual_srvs::SetJointAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manual_srvs::SetJointAngles >::value();
  }
  static const char* value(const ::manual_srvs::SetJointAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manual_srvs::SetJointAnglesResponse> should match
// service_traits::DataType< ::manual_srvs::SetJointAngles >
template<>
struct DataType< ::manual_srvs::SetJointAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::manual_srvs::SetJointAngles >::value();
  }
  static const char* value(const ::manual_srvs::SetJointAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANUAL_SRVS_MESSAGE_SETJOINTANGLES_H
