// Generated by gencpp from file mycobot_communication/SetEndType.msg
// DO NOT EDIT!


#ifndef MYCOBOT_COMMUNICATION_MESSAGE_SETENDTYPE_H
#define MYCOBOT_COMMUNICATION_MESSAGE_SETENDTYPE_H

#include <ros/service_traits.h>


#include <mycobot_communication/SetEndTypeRequest.h>
#include <mycobot_communication/SetEndTypeResponse.h>


namespace mycobot_communication
{

struct SetEndType
{

typedef SetEndTypeRequest Request;
typedef SetEndTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEndType
} // namespace mycobot_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mycobot_communication::SetEndType > {
  static const char* value()
  {
    return "9dfdf50aef7688b8c7d43efb64190a81";
  }

  static const char* value(const ::mycobot_communication::SetEndType&) { return value(); }
};

template<>
struct DataType< ::mycobot_communication::SetEndType > {
  static const char* value()
  {
    return "mycobot_communication/SetEndType";
  }

  static const char* value(const ::mycobot_communication::SetEndType&) { return value(); }
};


// service_traits::MD5Sum< ::mycobot_communication::SetEndTypeRequest> should match
// service_traits::MD5Sum< ::mycobot_communication::SetEndType >
template<>
struct MD5Sum< ::mycobot_communication::SetEndTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::SetEndType >::value();
  }
  static const char* value(const ::mycobot_communication::SetEndTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::SetEndTypeRequest> should match
// service_traits::DataType< ::mycobot_communication::SetEndType >
template<>
struct DataType< ::mycobot_communication::SetEndTypeRequest>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::SetEndType >::value();
  }
  static const char* value(const ::mycobot_communication::SetEndTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mycobot_communication::SetEndTypeResponse> should match
// service_traits::MD5Sum< ::mycobot_communication::SetEndType >
template<>
struct MD5Sum< ::mycobot_communication::SetEndTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::SetEndType >::value();
  }
  static const char* value(const ::mycobot_communication::SetEndTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::SetEndTypeResponse> should match
// service_traits::DataType< ::mycobot_communication::SetEndType >
template<>
struct DataType< ::mycobot_communication::SetEndTypeResponse>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::SetEndType >::value();
  }
  static const char* value(const ::mycobot_communication::SetEndTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYCOBOT_COMMUNICATION_MESSAGE_SETENDTYPE_H
