// Generated by gencpp from file mycobot_communication/SetEndTypeRequest.msg
// DO NOT EDIT!


#ifndef MYCOBOT_COMMUNICATION_MESSAGE_SETENDTYPEREQUEST_H
#define MYCOBOT_COMMUNICATION_MESSAGE_SETENDTYPEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mycobot_communication
{
template <class ContainerAllocator>
struct SetEndTypeRequest_
{
  typedef SetEndTypeRequest_<ContainerAllocator> Type;

  SetEndTypeRequest_()
    : Status(0)  {
    }
  SetEndTypeRequest_(const ContainerAllocator& _alloc)
    : Status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _Status_type;
  _Status_type Status;





  typedef boost::shared_ptr< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEndTypeRequest_

typedef ::mycobot_communication::SetEndTypeRequest_<std::allocator<void> > SetEndTypeRequest;

typedef boost::shared_ptr< ::mycobot_communication::SetEndTypeRequest > SetEndTypeRequestPtr;
typedef boost::shared_ptr< ::mycobot_communication::SetEndTypeRequest const> SetEndTypeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator1> & lhs, const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Status == rhs.Status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator1> & lhs, const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mycobot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fa862b628cefe7464ed489433f1bba8";
  }

  static const char* value(const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fa862b628cefe74ULL;
  static const uint64_t static_value2 = 0x64ed489433f1bba8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mycobot_communication/SetEndTypeRequest";
  }

  static const char* value(const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 Status\n"
"\n"
;
  }

  static const char* value(const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEndTypeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mycobot_communication::SetEndTypeRequest_<ContainerAllocator>& v)
  {
    s << indent << "Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYCOBOT_COMMUNICATION_MESSAGE_SETENDTYPEREQUEST_H
