// Generated by gencpp from file mycobot_communication/SetFreshMode.msg
// DO NOT EDIT!


#ifndef MYCOBOT_COMMUNICATION_MESSAGE_SETFRESHMODE_H
#define MYCOBOT_COMMUNICATION_MESSAGE_SETFRESHMODE_H

#include <ros/service_traits.h>


#include <mycobot_communication/SetFreshModeRequest.h>
#include <mycobot_communication/SetFreshModeResponse.h>


namespace mycobot_communication
{

struct SetFreshMode
{

typedef SetFreshModeRequest Request;
typedef SetFreshModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFreshMode
} // namespace mycobot_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mycobot_communication::SetFreshMode > {
  static const char* value()
  {
    return "9dfdf50aef7688b8c7d43efb64190a81";
  }

  static const char* value(const ::mycobot_communication::SetFreshMode&) { return value(); }
};

template<>
struct DataType< ::mycobot_communication::SetFreshMode > {
  static const char* value()
  {
    return "mycobot_communication/SetFreshMode";
  }

  static const char* value(const ::mycobot_communication::SetFreshMode&) { return value(); }
};


// service_traits::MD5Sum< ::mycobot_communication::SetFreshModeRequest> should match
// service_traits::MD5Sum< ::mycobot_communication::SetFreshMode >
template<>
struct MD5Sum< ::mycobot_communication::SetFreshModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::SetFreshMode >::value();
  }
  static const char* value(const ::mycobot_communication::SetFreshModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::SetFreshModeRequest> should match
// service_traits::DataType< ::mycobot_communication::SetFreshMode >
template<>
struct DataType< ::mycobot_communication::SetFreshModeRequest>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::SetFreshMode >::value();
  }
  static const char* value(const ::mycobot_communication::SetFreshModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mycobot_communication::SetFreshModeResponse> should match
// service_traits::MD5Sum< ::mycobot_communication::SetFreshMode >
template<>
struct MD5Sum< ::mycobot_communication::SetFreshModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::SetFreshMode >::value();
  }
  static const char* value(const ::mycobot_communication::SetFreshModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::SetFreshModeResponse> should match
// service_traits::DataType< ::mycobot_communication::SetFreshMode >
template<>
struct DataType< ::mycobot_communication::SetFreshModeResponse>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::SetFreshMode >::value();
  }
  static const char* value(const ::mycobot_communication::SetFreshModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYCOBOT_COMMUNICATION_MESSAGE_SETFRESHMODE_H
