// Generated by gencpp from file mycobot_communication/SetToolReference.msg
// DO NOT EDIT!


#ifndef MYCOBOT_COMMUNICATION_MESSAGE_SETTOOLREFERENCE_H
#define MYCOBOT_COMMUNICATION_MESSAGE_SETTOOLREFERENCE_H

#include <ros/service_traits.h>


#include <mycobot_communication/SetToolReferenceRequest.h>
#include <mycobot_communication/SetToolReferenceResponse.h>


namespace mycobot_communication
{

struct SetToolReference
{

typedef SetToolReferenceRequest Request;
typedef SetToolReferenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetToolReference
} // namespace mycobot_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mycobot_communication::SetToolReference > {
  static const char* value()
  {
    return "eed7ebf6b157baae92879470642b26d9";
  }

  static const char* value(const ::mycobot_communication::SetToolReference&) { return value(); }
};

template<>
struct DataType< ::mycobot_communication::SetToolReference > {
  static const char* value()
  {
    return "mycobot_communication/SetToolReference";
  }

  static const char* value(const ::mycobot_communication::SetToolReference&) { return value(); }
};


// service_traits::MD5Sum< ::mycobot_communication::SetToolReferenceRequest> should match
// service_traits::MD5Sum< ::mycobot_communication::SetToolReference >
template<>
struct MD5Sum< ::mycobot_communication::SetToolReferenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::SetToolReference >::value();
  }
  static const char* value(const ::mycobot_communication::SetToolReferenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::SetToolReferenceRequest> should match
// service_traits::DataType< ::mycobot_communication::SetToolReference >
template<>
struct DataType< ::mycobot_communication::SetToolReferenceRequest>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::SetToolReference >::value();
  }
  static const char* value(const ::mycobot_communication::SetToolReferenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mycobot_communication::SetToolReferenceResponse> should match
// service_traits::MD5Sum< ::mycobot_communication::SetToolReference >
template<>
struct MD5Sum< ::mycobot_communication::SetToolReferenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::SetToolReference >::value();
  }
  static const char* value(const ::mycobot_communication::SetToolReferenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::SetToolReferenceResponse> should match
// service_traits::DataType< ::mycobot_communication::SetToolReference >
template<>
struct DataType< ::mycobot_communication::SetToolReferenceResponse>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::SetToolReference >::value();
  }
  static const char* value(const ::mycobot_communication::SetToolReferenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYCOBOT_COMMUNICATION_MESSAGE_SETTOOLREFERENCE_H
